fix: Standardize event callback signatures to 4 args
All event_callback calls now use consistent signature:
  await event_callback(stage, status, payload, latency_ms)

Fixed callbacks in:
- _classify_node: Added {}, None args
- _route_deterministic_node: Added {}, None args
- _prefetch_node: Added None arg to error case
- _rag_node: Added {}, None args
- _verify_node: Added {}, None args to both places

This fixes TypeError: callback() missing 2 required positional arguments